[module]
[module.hugoVersion]
extended = true
min = "0.87.0"
max = "0.147.1"

# Настройки языка по умолчанию
defaultContentLanguage = "en"


[params]
  # ... параметры темы Blowfish ...
  [params.social]
    telegram = "https://t.me/jatozan"
    facebook = "jatozan"
    instagram = "https://instagram.com/jatozan"
    youtube = "https://youtube.com/jatozan"
