title = "Главная страница"
disabled = false
languageCode = "ru"
languageName = "Русский"
weight = 2
contentDir = "content/ru"

[params]
  displayName = "Русский"
  isoCode = "ru"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"
